#============================================================================================#   
#                                      silva－MD                                             # 
#                                                                                             # 
#                                   VERSION ：2．5．0                                          # 
#                                                                                             # 
#                                                                                             # 
#           ██████╗ ██╗███████╗████████╗███████╗██████╗     ███╗   ███╗██████╗                # 
#          ██╔════╝ ██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗    ████╗ ████║██╔══██╗               # 
#          ██║  ███╗██║█████╗     ██║   █████╗  ██║  ██║    ██╔████╔██║██║  ██║               # 
#          ██║   ██║██║██╔══╝     ██║   ██╔══╝  ██║  ██║    ██║╚██╔╝██║██║  ██║               # 
#          ╚██████╔╝██║██║        ██║   ███████╗██████╔╝    ██║ ╚═╝ ██║██████╔╝               # 
#           ╚═════╝ ╚═╝╚═╝        ╚═╝   ╚══════╝╚═════╝     ╚═╝     ╚═╝╚═════╝                # 
#                                                                                             # 
#                                                                                             # 
#                                                                                             # 
#                                                                                             # 
#=============================================================================================# 
#                                                                 
#    * @project_name : x-silva-md
#    * @author : @SilvaTech
#    * @tiktok : https://www.tiktok.com/@silva.edits6
#    * @description : Gifted-Md ,A Multi-functional whatsapp bot md.
#    * @version 2.5.0
# 
# Don't change this [ /SilvaTech/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/mouricedevs/gifted-md
RUN git clone https://github.com/Sylivanu/x-silva-md /root/Silva
WORKDIR /root/Silva/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
